// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7Vt11DiR1RBVmeKSnq-kjM0a-hyIGUE4',
    appId: '1:210244834675:web:c69ede7ed915bc97502106',
    messagingSenderId: '210244834675',
    projectId: 'namnam-18d31',
    authDomain: 'namnam-18d31.firebaseapp.com',
    storageBucket: 'namnam-18d31.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkkyoypiwqfeCdEQX325nS-1b-bDK3QAg',
    appId: '1:210244834675:android:478ae07661381255502106',
    messagingSenderId: '210244834675',
    projectId: 'namnam-18d31',
    storageBucket: 'namnam-18d31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcfTicUje73hDWyqBYw_pSB8-XhR3sChc',
    appId: '1:210244834675:ios:60848338fd7ec8b8502106',
    messagingSenderId: '210244834675',
    projectId: 'namnam-18d31',
    storageBucket: 'namnam-18d31.firebasestorage.app',
    iosBundleId: 'com.example.namnam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcfTicUje73hDWyqBYw_pSB8-XhR3sChc',
    appId: '1:210244834675:ios:60848338fd7ec8b8502106',
    messagingSenderId: '210244834675',
    projectId: 'namnam-18d31',
    storageBucket: 'namnam-18d31.firebasestorage.app',
    iosBundleId: 'com.example.namnam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7Vt11DiR1RBVmeKSnq-kjM0a-hyIGUE4',
    appId: '1:210244834675:web:bac3eb69400b1c5d502106',
    messagingSenderId: '210244834675',
    projectId: 'namnam-18d31',
    authDomain: 'namnam-18d31.firebaseapp.com',
    storageBucket: 'namnam-18d31.firebasestorage.app',
  );
}
